import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { Navbar } from "../components/Navbar";
import { Menu } from "../components/Menu";
import raznimeApi from "./api/raznime";
import Image from "next/image";
import Link from "next/link";
import { AnimeCard } from "../components/AnimeCard";

const Home: NextPage = () => {
  const [ongoing, setOngoing] = useState<Array<any>>([
    { animeId: 1, animeImg: "/" },
  ]);

  useEffect(() => {
    raznimeApi
      .get("/top-airing")
      .then((response) => {
        console.log(response.data);
        setOngoing(response.data);
      })
      .catch((err) => console.log(err));
    console.log(ongoing);
  }, []);

  return (
    <div>
      <Head>
        <title>Anime Ingfo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Navbar />
        <Menu />
      </nav>
      <main className="bg-slate-100">
        <div className="banner w-full h-96 bg-gradient-to-br from-violet-500 to-fuchsia-500"></div>
        <h1 className="text-3xl text-center mb-5 mt-10 font-bold">
          Top Ongoing Animes
        </h1>
        <div className="grid grid-cols-2 gap-5 mx-5 md:grid-cols-4 pb-10">
          {ongoing.map((anime) => {
            return <AnimeCard anime={anime} key={anime.animeId} />;
          })}
        </div>
      </main>
      <footer className="mt-10 p-5 text-center bg-blue-500">
        &copy; INGFOOS
      </footer>
    </div>
  );
};

export default Home;
