import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { Navbar } from "../components/Navbar";
import { Menu } from "../components/Menu";
import raznimeApi from "./api/raznime";
import Image from "next/image";
import Link from "next/link";
import { AnimeCard } from "../components/AnimeCard";
import { EpisodeCard } from "../components/EpisodeCard";

const Home: NextPage = () => {
  const [recentRelease, setRecentRelease] = useState<Array<any>>([
    { episodeId: 1, animeImg: "/" },
  ]);

  useEffect(() => {
    raznimeApi
      .get("/recent-release")
      .then((response:any) => {
        console.log(response.data);
        setRecentRelease(response.data);
      })
      .catch((err:any) => console.log(err));
    console.log(recentRelease);
  }, []);

  return (
    <div>
      <Head>
        <title>Anime Ingfo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Navbar />
        <Menu />
      </nav>
      <main className="bg-slate-100">
        <div className="banner flex flex-col items-center justify-center w-full h-96 bg-gradient-to-br from-violet-500 to-fuchsia-500">
          <h1 className="text-4xl text-white">Welcome to Anime Ingfo</h1>
        </div>
        <h1 className="text-3xl text-center mb-5 mt-10 font-bold">
          Recently Released
        </h1>
        <div className="grid grid-cols-2 gap-5 mx-5 md:grid-cols-5 sm:grid-cols-3 pb-10">
          {recentRelease.map((episode) => {
            return <EpisodeCard episode={episode} key={episode.episodeId} />;
          })}
        </div>
      </main>
      <footer className="p-5 text-center bg-blue-500">
        &copy; INGFOOS
      </footer>
    </div>
  );
};

export default Home;
