import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import { Navbar } from '../components/Navbar'
import styles from '../styles/Home.module.css'
import raznimeApi from './api/raznime'

const Home: NextPage = () => {

  async function fetchAPI() {
    raznimeApi.get('/anime-details/one-piece')
    .then(response => {console.log(response.data)})
    .catch(err => console.log(err))
  }
  
  useEffect(() => {
    fetchAPI();
  },[])

  return (
    <div>
      <Head>
        <title>Daftar Anime Ku</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Navbar />
      </nav>
      <main className='text-3xl'>
        <div className='banner w-full h-96 bg-slate-300'></div>
      </main>
      <footer></footer>
    </div>
  )
}

export default Home
